spring.application.name=spendwisebackend
spring.datasource.url=jdbc:postgresql://dpg-d7euh3vaqgkc739tigv0-a:5432/spendwise_ad1n
spring.datasource.username=spendwise_ad1n_user
spring.datasource.password=Dj0wPSrINhGVurUj6dlfoCd2UFeMINRc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true